version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
  # Separate group for pytorch deps.
  # https://github.com/dependabot/dependabot-core/issues/4364
  - package-ecosystem: pip
    directory: "/build_tools"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
