# Copyright 2025 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Update IREE dependencies

on:
  workflow_dispatch:
  # schedule:
  #   # Weekdays at 11:00 AM UTC = 03:00 AM PST / 04:00 AM PDT
  #   - cron: "0 11 * * 1-5"

jobs:
  update-iree:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: "Setting up Python"
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: 3.11

      - name: Run auto dependency update
        uses: romoh/dependencies-autoupdate@7c3c46ae7d2e10fee175b73f21fee86cc0689a01 # untagged
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr-branch: integrates/iree
          update-command: "'./build_tools/update_iree_version_pins.py'"
          update-path: "'${{ github.workspace }}'"
          on-changes-command: "'echo hi'"
